variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse4.25/eclipse
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

before_script:
  - git submodule update --init

build_and_test_job:
  tags: [yuria]
  script:
    - timeout 5m ant unit-tests som-tests

benchmark_y1:
  tags: [yuria]
  needs: ["build_and_test_job"]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria
  after_script:
    - sudo reown-project.sh

benchmark_y2:
  tags: [yuria2]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria2
  after_script:
    - sudo reown-project.sh

benchmark_y3:
  tags: [yuria3]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria3
  after_script:
    - sudo reown-project.sh

benchmark_completion:
  tags: [yuria]
  needs: ["benchmark_y1", "benchmark_y2", "benchmark_y3"]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion codespeed.conf

kompos_and_dym_tests:
  tags: [yuria]
  needs: ["benchmark_y1"]
  script:
    - ant jacoco-lib jar dynamic-metrics-tests superinstructions-tests
    - (cd tools/kompos && npm install . && npm -s run verify && npm test)

replay_tests:
  tags: [yuria2]
  needs: ["benchmark_y2"]
  script:
    - timeout 30m ant replay-tests

# Disabled due to breaking changes in the tracing infrastructure. Not fixed to make merge of Snapshotting PR(#293) easier.
#snapshot_tests:
#  tags: [benchmarks, infinity]
#  script:
#    - timeout 10m ant snapshot-tests

svm_tests_and_style_checks:
  tags: [yuria3]
  needs: ["benchmark_y3"]
  script:
    - ant native-tests
    - ant checkstyle
    - ant eclipseformat-check

benchmark_nightly_job:
  tags: [benchmarks, infinity]
  allow_failure: true
  only:
    - triggers
  script:
    - ant compile
    - rebench --experiment="CI Benchmark Run Pipeline ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf nightly
    - rebench --experiment="CI Benchmark Run Pipeline ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-Savina-tracing
  after_script:
    - sudo reown-project.sh

build_virtualbox:
  tags: [benchmarks, infinity]
  only:
    - triggers
  script:
    - artifact/virtualbox.sh
