stages:
  - build-and-test
  - benchmark
  - full-test
  - virtualbox-image

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse4.25/eclipse
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

before_script:
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [yuria]
  script:
    - timeout 5m ant unit-tests som-tests

kompos_and_dym_tests:
  stage: full-test
  tags: [yuria]
  script:
    - ant jacoco-lib jar dynamic-metrics-tests superinstructions-tests
    - (cd tools/kompos && npm install . && npm -s run verify && npm test)

replay_tests:
  stage: full-test
  tags: [yuria2]
  script:
    - timeout 30m ant replay-tests

# Disabled due to breaking changes in the tracing infrastructure. Not fixed to make merge of Snapshotting PR(#293) easier.
#snapshot_tests:
#  stage: full-test
#  tags: [benchmarks, infinity]
#  script:
#    - timeout 10m ant snapshot-tests

svm_tests:
  stage: full-test
  tags: [yuria3]
  script:
    - ant native-tests

style_checks:
  stage: full-test
  tags: [yuria3]
  script:
    - ant checkstyle
    - ant eclipseformat-check


benchmark_y1:
  stage: benchmark
  tags: [yuria]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria

benchmark_y2:
  stage: benchmark
  tags: [yuria2]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria2

benchmark_y3:
  stage: benchmark
  tags: [yuria3]
  allow_failure: true
  script:
    - ant compile
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-CI m:yuria3

benchmark_completion:
  stage: full-test
  tags: [yuria]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion codespeed.conf

benchmark_nightly_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  only:
    - triggers
  script:
    - ant compile
    - rebench --experiment="CI Benchmark Run Pipeline ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf nightly
    - rebench --experiment="CI Benchmark Run Pipeline ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c codespeed.conf SOMns-Savina-tracing

build_virtualbox:
  stage: virtualbox-image
  tags: [benchmarks, infinity]
  only:
    - triggers
  script:
    - artifact/virtualbox.sh
